---
- hosts: all
  gather_facts: True
  tasks:
    - name: Update OS
      apt: upgrade=dist

    - name: Install MySQL
      apt: name=mysql-server state=installed

    - name: Install Apt Pip
      apt: name=python-pip state=installed

    - name: Install python-dev
      apt: name=python-dev state=installed

    - name: Install Pip
      pip: name=pip state=latest

    - name: Install Virtualenv
      pip: name=virtualenv

    - name: Install Virtualenvwrapper
      pip: name=virtualenvwrapper

    - name: Activate virtualenv on login
      command: echo 'source /var/www/hss/env/bin/activate' > /home/vagrant/.bash_profile

    - name: Add 'hss' symlink to vagrant homedir
      file: src=/var/www/hss dest=/home/vagrant/hss state=link

    - name: Install Python-MySQL Dependencies
      apt: name=libmysqlclient-dev state=installed

    - name: Install MySQL-python
      apt: name=python-mysqldb state=installed

    - name: Ensure MySQL is running
      service: name=mysql state=started enabled=true

    - name: Add hssonline MySQL DB
      mysql_db: name=hssonline state=present

    - name: Add hssweb_temp MySQL DB
      mysql_db: name=hssweb_temp state=present

    - name: Add conferenceUser MySQL user
      mysql_user: name=conferenceUser password=conferencePass priv=conference.*:ALL/test_conference.*:ALL

    - name: Add electionUser MySQL user
      mysql_user: name=electionUser password=electionPass priv=election.*:ALL/test_election.*:ALL

    - name: Add electionUser MySQL user
      mysql_user: name=hssonline priv=hssonline.*:ALL/hssweb_unittests.*:ALL/hssweb_temp.*:ALL
