---
- hosts: all
  gather_facts: True
  vars:
      hss_root: '/home/vagrant/hss'
  tasks:
    - name: Update OS
      apt: upgrade=dist

    - name: Install MySQL
      apt: name=mysql-server state=installed

    - name: Install Apt Pip
      apt: name=python-pip state=installed

    - name: Install python-dev
      apt: name=python-dev state=installed

    - name: Install Python-MySQL dependency
      apt: name=libmysqlclient-dev state=installed

    - name: Install MySQL-python (needed by Ansible)
      apt: name=python-mysqldb state=installed

    - name: Install Pip
      pip: name=pip state=latest

    - name: Install Virtualenv
      pip: name=virtualenv

    - name: Install hssonline requirements to a virtualenv directory named "env"
      pip: requirements={{hss_root}}/newhssonline/requirements.txt virtualenv={{hss_root}}/env virtualenv_site_packages=yes

    - name: Activate virtualenv on login
      copy: content="source {{hss_root}}/env/bin/activate" dest=/home/vagrant/.bash_profile owner=vagrant group=vagrant

    - name: Ensure MySQL is running
      service: name=mysql state=started enabled=true

    - name: Add MySQL DBs
      mysql_db: name={{ item }} state=present
      with_items: ['hssonline', 'test_hssonline', 'conference', 'election']

    - name: Add MySQL users
      mysql_user: name={{ item.name }} password={{ item.password }} priv={{ item.db }}.*:ALL/test_{{ item.db }}.*:ALL
      with_items:
          - { name: 'hssonline', db: 'hssonline', password: 'foo' }
          - { name: 'conferenceUser', db: 'conference', password: 'conferencePass' }
          - { name: 'electionUser', db: 'election', password: 'electionPass' }
